In [ ]:
Regression Assignment Objective:
The objective of this assignment is to evaluate your understanding of regression techniques in
supervised learning by applying them to a real-world dataset.
Dataset:
Use the California Housing dataset available in the sklearn library. This dataset contains
information about various features of houses in California and their respective median prices.
Key Components to be Fulfilled:
1. Loading and Preprocessing (2 marks):
● Load the California Housing dataset using the fetch_california_housing function
from sklearn.
● Convert the dataset into a pandas DataFrame for easier handling. Handle
missing values (if any) and perform necessary feature scaling (e.g.,
standardization).
● Explain the preprocessing steps you performed and justify why they are
necessary for this dataset.

2. Regression Algorithm Implementation (5 marks):
● Implement the following regression algorithms:
○ Linear Regression
○ Decision Tree Regressor
○ Random Forest Regressor
○ Gradient Boosting Regressor
○ Support Vector Regressor (SVR)
● For each algorithm: Provide a brief explanation of how it works. Explain why it
might be suitable for this dataset.
3. Model Evaluation and Comparison (2 marks):
● Evaluate the performance of each algorithm using the following metrics:
○ Mean Squared Error (MSE)
○ Mean Absolute Error (MAE)
○ R-squared Score (R2)
● Compare the results of all models and identify: The best-performing algorithm
with justification and the worst-performing algorithm with reasoning.

4. Timely Submission (1 mark):
● Submit your code in a Jupyter Notebook format via a GitHub link.
● Ensure that your code is well-documented and explanations are clear and
concise.
● Submission Guidelines: Use Python and Jupyter Notebook for implementation.
Submit the GitHub repository link containing the code and all necessary files.
Ensure proper documentation, including code comments and markdown
explanations.

In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing

# 1. Loading and Preprocessing (2 marks):
# ● Load the California Housing dataset using the fetch_california_housing function from sklearn.
# ● Convert the dataset into a pandas DataFrame for easier handling. Handle missing values (if any) and perform necessary feature scaling (e.g.,standardization).
# ● Explain the preprocessing steps you performed and justify why they are necessary for this dataset.

In [3]:
data = fetch_california_housing()

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [4]:
df = pd.DataFrame(data.data, columns=data.feature_names)

df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [5]:
data.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,))

In [6]:
df['MedHouseValue'] = data.target

In [7]:
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseValue
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [8]:
df.isnull().sum()

MedInc           0
HouseAge         0
AveRooms         0
AveBedrms        0
Population       0
AveOccup         0
Latitude         0
Longitude        0
MedHouseValue    0
dtype: int64

California Housing dataset contains no missing values, so no imputation needed.

In [10]:
scaler = StandardScaler()

X = scaler.fit_transform(df[data.feature_names])
y = df['MedHouseValue']

Scaling is essential especially for algorithms that are sensitive to feature magnitudes.

# 2. Regression Algorithm Implementation (5 marks):
# ● Implement the following regression algorithms:
# ○ Linear Regression
# ○ Decision Tree Regressor
# ○ Random Forest Regressor
# ○ Gradient Boosting Regressor
# ○ Support Vector Regressor (SVR)
# ● For each algorithm: Provide a brief explanation of how it works. Explain why it might be suitable for this dataset.

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Linear Regression

In [13]:
lr = LinearRegression()
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)

In [15]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR

# Decision Tree Regressor

In [16]:
dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)

# Random Forest Regressor

In [17]:
rf = RandomForestRegressor(n_estimators=200, random_state=42)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)

# Gradient Boosting Regressor

In [19]:
gbr = GradientBoostingRegressor(random_state=42)
gbr.fit(X_train, y_train)
gbr_pred = gbr.predict(X_test)

# Support Vector Regressor (SVR)

In [20]:
svr = SVR(kernel='rbf')
svr.fit(X_train, y_train)
svr_pred = svr.predict(X_test)

# 3. Model Evaluation and Comparison (2 marks):
# ● Evaluate the performance of each algorithm using the following metrics:
# ○ Mean Squared Error (MSE)
# ○ Mean Absolute Error (MAE)
# ○ R-squared Score (R2)
# ● Compare the results of all models and identify: The best-performing algorithm with justification and the worst-performing algorithm with reasoning.

In [21]:
def evaluate(y_true, y_pred):
    return {
        "MSE": mean_squared_error(y_true, y_pred),
        "MAE": mean_absolute_error(y_true, y_pred),
        "R2 Score": r2_score(y_true, y_pred)
    }

In [22]:
results = {
    "Linear Regression": evaluate(y_test, lr_pred),
    "Decision Tree": evaluate(y_test, dt_pred),
    "Random Forest": evaluate(y_test, rf_pred),
    "Gradient Boosting": evaluate(y_test, gbr_pred),
    "SVR": evaluate(y_test, svr_pred)
}

In [23]:
results

{'Linear Regression': {'MSE': 0.5558915986952442,
  'MAE': 0.5332001304956565,
  'R2 Score': 0.575787706032451},
 'Decision Tree': {'MSE': 0.4942716777366763,
  'MAE': 0.4537843265503876,
  'R2 Score': 0.6228111330554302},
 'Random Forest': {'MSE': 0.25401057726311893,
  'MAE': 0.3267962577882755,
  'R2 Score': 0.8061593124887589},
 'Gradient Boosting': {'MSE': 0.29399901242474274,
  'MAE': 0.37165044848436773,
  'R2 Score': 0.7756433164710084},
 'SVR': {'MSE': 0.3551984619989429,
  'MAE': 0.3977630963437874,
  'R2 Score': 0.7289407597956454}}

In [24]:
pd.DataFrame(results).T

                        MSE       MAE  R2 Score
Linear Regression  0.555892  0.533200  0.575788
Decision Tree      0.494272  0.453784  0.622811
Random Forest      0.254011  0.326796  0.806159
Gradient Boosting  0.293999  0.371650  0.775643
SVR                0.355198  0.397763  0.728941

# Best Model: Random Forest OR Gradient Boosting (usually best R2 score ~ 0.75–0.85)

# Reasons:
# Ensemble methods reduce variance (RF) and reduce bias (GBR).

# Can capture non-linear relationships better than Linear Regression and SVR.

In [ ]:
# Worst Model:  Decision Tree Regressor